apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-rental-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-rental-db
  labels:
    app: tool-rental-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool-rental-db
  template:
    metadata:
      labels:
        app: tool-rental-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "rental"
            - name: POSTGRES_USER
              value: "app"
            - name: POSTGRES_PASSWORD
              # Musí být stejné jako SPRING_DATASOURCE_PASSWORD v tool-rental-secret
              valueFrom:
                secretKeyRef:
                  name: tool-rental-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: tool-rental-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tool-rental-db
  labels:
    app: tool-rental-db
spec:
  type: ClusterIP
  selector:
    app: tool-rental-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

