apiVersion: v1
kind: Service
metadata:
  name: tool-rental
  labels:
    app: tool-rental
spec:
  type: ClusterIP
  selector:
    app: tool-rental
  ports:
    - name: http
      port: 80
      targetPort: 8080
